
import java.awt.AWTException;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.MenuItem;
import java.awt.PopupMenu;
import java.awt.SystemTray;
import java.awt.TrayIcon;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Line2D;
import java.awt.image.BufferedImage;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ylhaart
 */
public class WeekNumberTrayGUI extends javax.swing.JFrame {

    /**
     * Creates new form WeekNumberTrayGUI
     */
    public WeekNumberTrayGUI() {
        initComponents();

        int i = Calendar.getInstance().get(Calendar.WEEK_OF_YEAR);
        weekNumberLabel.setText("" + i);

        if (SystemTray.isSupported()) {
            SystemTray tray = SystemTray.getSystemTray();
            try {
                tray.add(new WeekTrayIcon(this));
            } catch (AWTException ex) {
                Logger.getLogger(WeekNumberTrayGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        weekNumberLabel = new javax.swing.JLabel();

        jLabel1.setText("Week number");

        weekNumberLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        weekNumberLabel.setText("XX");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(weekNumberLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(weekNumberLabel)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WeekNumberTrayGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WeekNumberTrayGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WeekNumberTrayGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WeekNumberTrayGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WeekNumberTrayGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel weekNumberLabel;
    // End of variables declaration//GEN-END:variables
}

class WeekTrayIcon extends TrayIcon implements ActionListener {

    static String EXIT_COMMAND = "exit";
    static String SHOW_COMMAND = "show";
    WeekNumberTrayGUI weekProgram;

    public WeekTrayIcon(WeekNumberTrayGUI t) {
        super(createIconImage(), "Week number");
        weekProgram = t;

        PopupMenu menu = new PopupMenu();

        MenuItem show = new MenuItem("Show");
        show.setActionCommand(SHOW_COMMAND);
        MenuItem exit = new MenuItem("Exit");
        exit.setActionCommand(EXIT_COMMAND);

        exit.addActionListener(this);
        show.addActionListener(this);
        menu.add(show);
        menu.addSeparator();
        menu.add(exit);

        setPopupMenu(menu);
    }

    static Image createIconImage() {
        BufferedImage r = new BufferedImage(16, 16, BufferedImage.TYPE_4BYTE_ABGR);
        Graphics2D g = r.createGraphics();
        g.setColor(Color.WHITE);
        g.fill(new Ellipse2D.Double(2, 2, 12, 12));
        g.setColor(Color.BLACK);
        g.draw(new Ellipse2D.Double(2, 2, 14, 14));
        g.draw(new Line2D.Double(8, 8, 10, 4));
        return r;
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getActionCommand().equals(EXIT_COMMAND)) {
            weekProgram.setVisible(false);
            weekProgram.dispose();
            SystemTray.getSystemTray().remove(this);
        }
        if (e.getActionCommand().equals(SHOW_COMMAND)) {
            weekProgram.setVisible(true);
            weekProgram.toFront();
        }
    }
}
